[package]
name = "rust0"
version = "0.1.0"
authors = ["Daniel Kullmann <daniel.kullmann@sap.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
http = "0.1.14"
hyper = "0.12"
reqwest = "0.9.5"
rust-ini = "0.13"
serde_json = "1.0"
shellexpand = "1.0.0"
tokio = "0.1.13"
